### PR TITLE
Add pulse width setting to Oscillator class for square waveforms

### PR DESCRIPTION
**Pull request by ndonald2**
### Summary

This change implements a configurable pulse width for the `Oscillator` class's square and polyBLEP square waveforms.

### Details

Motivation is to add a simple pulse width setting to the standard `Oscillator` class for utility as an audio waveform as well as modulation. The setting applies to both the non-bandlimited and bandlimited square waves. This ended up being rather simple.

### Audio Examples

_Dropbox links to wav files. All examples start at A=110Hz and go up 4 octaves from there._

* [Slow Sine Sweep of PW - Standard Square Wave (non-bandlimited)](https://www.dropbox.com/s/tnjsqgd0oe0gj7b/PW%20Sweep%20-%205s%20-%20Non%20Bandimited.wav?dl=0)
* [Slow Sine Sweep of PW - polyBLEP Square Wave (bandlimited)](https://www.dropbox.com/s/vhj5e2k12j9cui7/PW%20Sweep%20-%205s%20-%20Bandimited.wav?dl=0)
* [2.5hz Sine PWM - Standard Square Wave (non-bandlimited)](https://www.dropbox.com/s/tlfgnwbyhy8ar4v/PWM%202.5hz%20-%20Non%20Bandlimited.wav?dl=0)
* [2.5hz Sine PWM - polyBLEP Square Wave (bandlimited)](https://www.dropbox.com/s/vwh9ixx67jadngr/PWM%202.5hz%20-%20Bandlimited.wav?dl=0)

### Feedback/Questions

* Anything I can do better in the implementation or to follow DaisySP codebase guidelines?
* I followed the method naming `SetPw` from `BlOsc` for consistency.
* Does it make sense the way I broke out `pw_` and `pw_rad_` (pre-multiplied by two pi) to avoid extra audio rate multiplications or divisions?
* I assume it makes sense to keep `WAVE_SQUARE` and `WAVE_POLYBLEP_SQUARE` as the waveform enum names for compatibility, though these are not technically just square anymore.
* Due to inverting amplifiers in the analog signal path, the pulse width of the waveform when using it as an audio output may not actually be precisely as set, it may be inverted (e.g. a pulse width of `0.25` may result in the wave being "high" for 75% of the time instead of 25%). However when used as an LFO or other internal modulation source the pulse width does match the setting.
* Please let me know if you'd like any more examples or info!

### CODE REVIEW

**Comment by ndonald2** [comment]
Please note the Dropbox web player uses audio compression so there will be some compression artifacts if you play the examples there. Recommend downloading them. Here's a link to download the whole set of examples:

https://www.dropbox.com/sh/3ltbbfl3uekdded/AABrC2XmVvwlurAg9EcyRQfKa?dl=1

**Comment by stephenhensley** [comment]
Hi @ndonald2!

Thanks for the awesome contribution! This looks great.
After a quick look, I think this is all good.

The style issues look easy to resolve manually.
If you clang-format installed, you can usually use the `./util/fix_style.sh` script to clean up any issues as well.
If you want to locally check style before pushing, you can do:
```
./ci/run-clang-format.py -r Source
```

>I assume it makes sense to keep WAVE_SQUARE and WAVE_POLYBLEP_SQUARE as the waveform enum names for compatibility, though these are not technically just square anymore.

I personally think this is okay, especially since the pulse-threshold is precomputed when set, and defaults to 50%

**Comment by ndonald2** [comment]
Thanks @stephenhensley! I think I was able to fix the style errors. `./util/fix_style.sh` makes a lot of changes to other files so I just ran `clang-format` on the files I changed.

**Comment by stephenhensley** [comment]
Awesome!

Everything looks good. I had a chance to play with it a little bit earlier, and it works great.

Thanks again for the contribution!!

**Pull request merged**
