### PR TITLE
Verb memory fix

### PR DESCRIPTION
**Pull request by stephenhensley**
MAX Delay size was set to 32kB, but was never checked with any settings.

Added a check to return 1 if it exceeds expected memory, and updated documentation.

### CODE REVIEW

**Comment by csounder** [comment]
Great fix.

Don't you think it would be nice if you told everyone that this was all based on Csound code - like your adaptation of this reverbsc opcode in Csound?

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by csounder** [comment]
Awesome!!! I do see that, in the code you do state that it was ported from Csound and that you list the original authors of the algorithms under the hood!  Wonderful.  It is especially inspiring to my Csound students and to the international Csound community of users and developers!!! 

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by stephenhensley** [comment]
@csounder 

Yes, each module has the source of the original source code and any contributors listed in the Credits section of the header file.

This all gets parsed out to the daisysp_reference.pdf documentation that can be found in the doc/ folder

**Comment by stephenhensley** [comment]
@csounder Actually, good catch. This one has the original credits in the implementation which won't get processed into the documentation. I'll fix this shortly so the reference material gives proper credit!

**Comment by csounder** [comment]
You are doing awesome and important work Stephen!  Can't wait to use, share, and teach with it!

Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Comment by stephenhensley** [comment]
@csounder 

Thanks Dr. B! I appreciate the kind words. 

I'd love to catch up soon; it's been a long time! I'll send you an email sometime this weekend.

**Comment by csounder** [comment]
Stephen,

That would be awesome.  


Dr. Richard Boulanger
Professor
Electronic Production and Design
Berklee College of Music

**Pull request merged**
