### PR TITLE
[CMake] Added missing files of phaser effect.

### PR DESCRIPTION
**Pull request by COx2**
Hello, DaisySP team.

When I was developing my application, I found a problem that could not resolve a reference of `daisysp::Phaser` functions.
The reason for this is that adding the Phaser source code in CMake is forgotten.

Please check it.

### CODE REVIEW

**Comment by stephenhensley** [comment]
Good catch! Thanks for adding it!

I believe this may conflict with #153 since it restructures the CMake file a bit.

I'll try to get that one merged later today to see if anything will need to change here.

Thanks again!

**Comment by stephenhensley** [comment]
Alright, I merged the other PR and there was a conflict. I was able to resolve it (by pushing to your master branch). 

Thanks for the PR! We appreciate the contribution!

**Comment by COx2** [comment]
Thank you for your accepting.
I have high hopes for this project.

BTW, I have created a project that showing an example of integration of DaisySP and JUCE6 with CMake.
Hope this helps the newbies.
https://github.com/COx2/juce_meets_DaisySP

**Comment by stephenhensley** [comment]
@COx2 oh very cool! I'll have to try it out this weekend or something! I actually have a very similar (though less featured) project set up with [DaisySP/JUCE/CMake](https://github.com/electro-smith/Daisy-Juce-Example). Definitely excited to see what you do with it!

**Comment by COx2** [comment]
Good stuff!!

**Pull request merged**
